import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@/providers/ChakraProvider";
import Navigation from "@/components/navBar/Navigation";
import { Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <Box as="main" display="flex">
          <Box as="aside" flex="1" />
          <ChakraProvider>{children}</ChakraProvider>
          <Box as="aside" flex="1" />
        </Box>
      </body>
    </html>
  );
}
